import { defineRegistryItems } from "./registry.js";

function uiFiles(component: string, files: string[]) {
  return files.map((file) => ({
    path: `../../packages/ui/src/components/ui/${component}/${file}`,
    type: "registry:ui" as const,
  }));
}

export const registryUi = defineRegistryItems([
  {
    name: "alert",
    type: "registry:ui",
    description: "Displays a message with an optional action.",
    dependencies: [],
    registryDependencies: [],
    files: uiFiles("alert", [
      "alert.svelte",
      "alert-action.svelte",
      "alert-description.svelte",
      "alert-title.svelte",
      "index.ts",
    ]),
  },
  {
    name: "badge",
    type: "registry:ui",
    description: "Labels a status, category, or count.",
    dependencies: [],
    registryDependencies: [],
    files: uiFiles("badge", ["badge.svelte", "index.ts"]),
  },
  {
    name: "avatar",
    type: "registry:ui",
    description: "Displays an image or fallback for a person or entity.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("avatar", [
      "avatar-root.svelte",
      "avatar-image.svelte",
      "avatar-fallback.svelte",
      "index.ts",
    ]),
  },
  {
    name: "button",
    type: "registry:ui",
    description: "Triggers an action or navigates to another page.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: ["local:spinner"],
    files: uiFiles("button", ["button.svelte", "index.ts"]),
  },
  {
    name: "breadcrumb",
    type: "registry:ui",
    description: "Shows the current page within a hierarchy.",
    dependencies: [],
    registryDependencies: [],
    files: uiFiles("breadcrumb", [
      "breadcrumb.svelte",
      "breadcrumb-ellipsis.svelte",
      "breadcrumb-item.svelte",
      "breadcrumb-link.svelte",
      "breadcrumb-list.svelte",
      "breadcrumb-page.svelte",
      "breadcrumb-separator.svelte",
      "index.ts",
    ]),
  },
  {
    name: "card",
    type: "registry:ui",
    description: "Groups related content and actions.",
    dependencies: [],
    registryDependencies: [],
    files: uiFiles("card", [
      "card.svelte",
      "card-action.svelte",
      "card-description.svelte",
      "card-footer.svelte",
      "card-frame.svelte",
      "card-frame-action.svelte",
      "card-frame-description.svelte",
      "card-frame-footer.svelte",
      "card-frame-header.svelte",
      "card-frame-title.svelte",
      "card-header.svelte",
      "card-panel.svelte",
      "card-part.svelte",
      "card-title.svelte",
      "index.ts",
    ]),
  },
  {
    name: "checkbox",
    type: "registry:ui",
    description: "Lets a user select or clear an option.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("checkbox", ["checkbox.svelte", "index.ts"]),
  },
  {
    name: "empty",
    type: "registry:ui",
    description: "Explains an empty state and its next actions.",
    dependencies: [],
    registryDependencies: [],
    files: uiFiles("empty", [
      "empty.svelte",
      "empty-content.svelte",
      "empty-description.svelte",
      "empty-header.svelte",
      "empty-media.svelte",
      "empty-part.svelte",
      "empty-title.svelte",
      "index.ts",
    ]),
  },
  {
    name: "frame",
    type: "registry:ui",
    description: "Frames related content with a header and footer.",
    dependencies: [],
    registryDependencies: [],
    files: uiFiles("frame", [
      "frame.svelte",
      "frame-description.svelte",
      "frame-footer.svelte",
      "frame-header.svelte",
      "frame-panel.svelte",
      "frame-title.svelte",
      "index.ts",
    ]),
  },
  {
    name: "input",
    type: "registry:ui",
    description: "Collects a single line of user input.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("input", ["input.svelte", "index.ts"]),
  },
  {
    name: "kbd",
    type: "registry:ui",
    description: "Represents keyboard input and shortcuts.",
    dependencies: [],
    registryDependencies: [],
    files: uiFiles("kbd", ["kbd.svelte", "kbd-group.svelte", "index.ts"]),
  },
  {
    name: "label",
    type: "registry:ui",
    description: "Labels an associated form control.",
    dependencies: [],
    registryDependencies: [],
    files: uiFiles("label", ["label.svelte", "index.ts"]),
  },
  {
    name: "meter",
    type: "registry:ui",
    description: "Shows a scalar measurement within a known range.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("meter", [
      "meter-root.svelte",
      "meter-label.svelte",
      "meter-track.svelte",
      "meter-indicator.svelte",
      "meter-value.svelte",
      "index.ts",
    ]),
  },
  {
    name: "progress",
    type: "registry:ui",
    description: "Shows progress toward completing a task.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("progress", [
      "progress-root.svelte",
      "progress-label.svelte",
      "progress-track.svelte",
      "progress-indicator.svelte",
      "progress-value.svelte",
      "index.ts",
    ]),
  },
  {
    name: "separator",
    type: "registry:ui",
    description: "Visually or semantically separates content.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("separator", ["separator.svelte", "index.ts"]),
  },
  {
    name: "skeleton",
    type: "registry:ui",
    description: "Reserves space while content is loading.",
    dependencies: [],
    registryDependencies: [],
    files: uiFiles("skeleton", ["skeleton.svelte", "index.ts"]),
  },
  {
    name: "spinner",
    type: "registry:ui",
    description: "Indicates that an operation is in progress.",
    dependencies: [],
    registryDependencies: [],
    files: uiFiles("spinner", ["spinner.svelte", "index.ts"]),
  },
  {
    name: "switch",
    type: "registry:ui",
    description: "Turns a setting on or off.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("switch", ["switch.svelte", "index.ts"]),
  },
  {
    name: "textarea",
    type: "registry:ui",
    description: "Collects multiline user input.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("textarea", ["textarea.svelte", "index.ts"]),
  },
  {
    name: "toggle",
    type: "registry:ui",
    description: "Switches a single control between pressed and unpressed states.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("toggle", ["toggle.svelte", "toggle-variants.ts", "index.ts"]),
  },
  {
    name: "toggle-group",
    type: "registry:ui",
    description: "Groups related toggle controls with shared selection behavior.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: ["local:separator", "local:toggle"],
    files: uiFiles("toggle-group", [
      "toggle-group-root.svelte",
      "toggle-group-item.svelte",
      "toggle-group-separator.svelte",
      "toggle-group-styles.ts",
      "context.ts",
      "index.ts",
    ]),
  },
]);
