import { defineRegistryItems } from "./registry.js";

const d4ParticleIds = [
  "p-accordion-1",
  "p-accordion-2",
  "p-accordion-3",
  "p-accordion-4",
  "p-card-1",
  "p-card-10",
  "p-card-11",
  "p-card-2",
  "p-card-3",
  "p-card-4",
  "p-card-5",
  "p-card-6",
  "p-card-7",
  "p-card-8",
  "p-card-9",
  "p-collapsible-1",
  "p-empty-1",
  "p-frame-1",
  "p-frame-2",
  "p-frame-3",
  "p-frame-4",
  "p-separator-1",
  "p-skeleton-1",
  "p-skeleton-2",
  "p-tabs-10",
  "p-tabs-11",
  "p-tabs-12",
  "p-tabs-13",
  "p-tabs-14",
  "p-tabs-15",
  "p-tabs-2",
  "p-tabs-3",
  "p-tabs-4",
  "p-tabs-5",
  "p-tabs-6",
  "p-tabs-7",
  "p-tabs-8",
  "p-tabs-9",
] as const;

function particle(name: (typeof d4ParticleIds)[number]) {
  const category = name.replace(/^p-/, "").replace(/-\d+$/, "");
  return {
    categories: [category],
    dependencies: ["@coss-sv/ui", "@hugeicons/core-free-icons@4.3.0", "@hugeicons/svelte@1.1.5"],
    description: `COSS ${category} example.`,
    files: [
      {
        path: `registry/default/particles/${name}.svelte`,
        type: "registry:block" as const,
      },
    ],
    name,
    registryDependencies: ["local:particle-metadata"],
    type: "registry:block" as const,
  };
}

export const registryParticles = defineRegistryItems([
  { ...particle("p-accordion-1"), name: "p-accordion-1" },
  { ...particle("p-accordion-2"), name: "p-accordion-2" },
  { ...particle("p-accordion-3"), name: "p-accordion-3" },
  { ...particle("p-accordion-4"), name: "p-accordion-4" },
  { ...particle("p-card-1"), name: "p-card-1" },
  { ...particle("p-card-10"), name: "p-card-10" },
  { ...particle("p-card-11"), name: "p-card-11" },
  { ...particle("p-card-2"), name: "p-card-2" },
  { ...particle("p-card-3"), name: "p-card-3" },
  { ...particle("p-card-4"), name: "p-card-4" },
  { ...particle("p-card-5"), name: "p-card-5" },
  { ...particle("p-card-6"), name: "p-card-6" },
  { ...particle("p-card-7"), name: "p-card-7" },
  { ...particle("p-card-8"), name: "p-card-8" },
  { ...particle("p-card-9"), name: "p-card-9" },
  { ...particle("p-collapsible-1"), name: "p-collapsible-1" },
  { ...particle("p-empty-1"), name: "p-empty-1" },
  { ...particle("p-frame-1"), name: "p-frame-1" },
  { ...particle("p-frame-2"), name: "p-frame-2" },
  { ...particle("p-frame-3"), name: "p-frame-3" },
  { ...particle("p-frame-4"), name: "p-frame-4" },
  { ...particle("p-separator-1"), name: "p-separator-1" },
  { ...particle("p-skeleton-1"), name: "p-skeleton-1" },
  { ...particle("p-skeleton-2"), name: "p-skeleton-2" },
  { ...particle("p-tabs-10"), name: "p-tabs-10" },
  { ...particle("p-tabs-11"), name: "p-tabs-11" },
  { ...particle("p-tabs-12"), name: "p-tabs-12" },
  { ...particle("p-tabs-13"), name: "p-tabs-13" },
  { ...particle("p-tabs-14"), name: "p-tabs-14" },
  { ...particle("p-tabs-15"), name: "p-tabs-15" },
  { ...particle("p-tabs-2"), name: "p-tabs-2" },
  { ...particle("p-tabs-3"), name: "p-tabs-3" },
  { ...particle("p-tabs-4"), name: "p-tabs-4" },
  { ...particle("p-tabs-5"), name: "p-tabs-5" },
  { ...particle("p-tabs-6"), name: "p-tabs-6" },
  { ...particle("p-tabs-7"), name: "p-tabs-7" },
  { ...particle("p-tabs-8"), name: "p-tabs-8" },
  { ...particle("p-tabs-9"), name: "p-tabs-9" },
]);
