import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { particleCatalog } from "../src/lib/particles/catalog.js";
import { defineRegistryItems } from "./registry.js";
import { registryUi } from "./registry-ui.js";

const registryRoot = dirname(fileURLToPath(import.meta.url));
const particleCatalogByName = new Map(particleCatalog.map((entry) => [entry.name, entry]));
const componentRegistryNames = new Set<string>(registryUi.map(({ name }) => name));

const particleIds = [
  "p-accordion-1",
  "p-accordion-2",
  "p-accordion-3",
  "p-accordion-4",
  "p-card-1",
  "p-card-10",
  "p-card-11",
  "p-card-2",
  "p-card-3",
  "p-card-4",
  "p-card-5",
  "p-card-6",
  "p-card-7",
  "p-card-8",
  "p-card-9",
  "p-collapsible-1",
  "p-empty-1",
  "p-frame-1",
  "p-frame-2",
  "p-frame-3",
  "p-frame-4",
  "p-separator-1",
  "p-skeleton-1",
  "p-skeleton-2",
  "p-tabs-10",
  "p-tabs-11",
  "p-tabs-12",
  "p-tabs-13",
  "p-tabs-14",
  "p-tabs-15",
  "p-tabs-2",
  "p-tabs-3",
  "p-tabs-4",
  "p-tabs-5",
  "p-tabs-6",
  "p-tabs-7",
  "p-tabs-8",
  "p-tabs-9",
  "p-button-1",
  "p-button-10",
  "p-button-11",
  "p-button-12",
  "p-button-13",
  "p-button-14",
  "p-button-15",
  "p-button-16",
  "p-button-17",
  "p-button-18",
  "p-button-19",
  "p-button-2",
  "p-button-20",
  "p-button-21",
  "p-button-22",
  "p-button-23",
  "p-button-24",
  "p-button-26",
  "p-button-27",
  "p-button-28",
  "p-button-29",
  "p-button-3",
  "p-button-30",
  "p-button-31",
  "p-button-32",
  "p-button-33",
  "p-button-34",
  "p-button-35",
  "p-button-36",
  "p-button-37",
  "p-button-38",
  "p-button-39",
  "p-button-4",
  "p-button-40",
  "p-button-41",
  "p-button-5",
  "p-button-6",
  "p-button-7",
  "p-button-8",
  "p-button-9",
  "p-checkbox-1",
  "p-checkbox-2",
  "p-checkbox-3",
  "p-checkbox-4",
  "p-checkbox-5",
  "p-checkbox-group-1",
  "p-checkbox-group-2",
  "p-checkbox-group-3",
  "p-checkbox-group-4",
  "p-checkbox-group-5",
  "p-radio-group-1",
  "p-radio-group-2",
  "p-radio-group-3",
  "p-radio-group-4",
  "p-radio-group-5",
  "p-radio-group-6",
  "p-slider-1",
  "p-slider-10",
  "p-slider-11",
  "p-slider-12",
  "p-slider-13",
  "p-slider-14",
  "p-slider-15",
  "p-slider-16",
  "p-slider-17",
  "p-slider-18",
  "p-slider-19",
  "p-slider-2",
  "p-slider-20",
  "p-slider-21",
  "p-slider-22",
  "p-slider-23",
  "p-slider-3",
  "p-slider-4",
  "p-slider-5",
  "p-slider-6",
  "p-slider-7",
  "p-slider-8",
  "p-slider-9",
  "p-switch-1",
  "p-switch-2",
  "p-switch-3",
  "p-switch-4",
  "p-switch-5",
  "p-switch-6",
  "p-switch-7",
  "p-switch-8",
  "p-switch-9",
  "p-toggle-1",
  "p-toggle-2",
  "p-toggle-3",
  "p-toggle-4",
  "p-toggle-5",
  "p-toggle-6",
  "p-toggle-7",
  "p-toggle-8",
  "p-toggle-group-1",
  "p-toggle-group-2",
  "p-toggle-group-3",
  "p-toggle-group-4",
  "p-toggle-group-5",
  "p-toggle-group-6",
  "p-toggle-group-7",
  "p-toggle-group-8",
  "p-toggle-group-9",
  "p-alert-dialog-1",
  "p-alert-dialog-2",
  "p-dialog-1",
  "p-dialog-2",
  "p-dialog-3",
  "p-dialog-4",
  "p-dialog-5",
  "p-dialog-6",
  "p-drawer-1",
  "p-drawer-10",
  "p-drawer-11",
  "p-drawer-12",
  "p-drawer-13",
  "p-drawer-14",
  "p-drawer-2",
  "p-drawer-3",
  "p-drawer-4",
  "p-drawer-5",
  "p-drawer-6",
  "p-drawer-7",
  "p-drawer-8",
  "p-drawer-9",
  "p-popover-1",
  "p-popover-2",
  "p-popover-3",
  "p-popover-4",
  "p-preview-card-1",
  "p-sheet-1",
  "p-sheet-2",
  "p-sheet-3",
  "p-tooltip-1",
  "p-tooltip-2",
  "p-tooltip-3",
  "p-tooltip-4",
  "p-breadcrumb-1",
  "p-breadcrumb-2",
  "p-breadcrumb-3",
  "p-breadcrumb-4",
  "p-breadcrumb-5",
  "p-breadcrumb-6",
  "p-breadcrumb-7",
  "p-calendar-1",
  "p-calendar-2",
  "p-calendar-3",
  "p-calendar-4",
  "p-calendar-5",
  "p-calendar-6",
  "p-calendar-7",
  "p-calendar-8",
  "p-calendar-9",
  "p-calendar-10",
  "p-calendar-11",
  "p-calendar-12",
  "p-calendar-13",
  "p-calendar-14",
  "p-calendar-15",
  "p-calendar-16",
  "p-calendar-17",
  "p-calendar-18",
  "p-calendar-19",
  "p-calendar-20",
  "p-calendar-21",
  "p-calendar-22",
  "p-calendar-23",
  "p-calendar-24",
  "p-calendar-25",
  "p-date-picker-1",
  "p-date-picker-2",
  "p-date-picker-3",
  "p-date-picker-4",
  "p-date-picker-5",
  "p-date-picker-6",
  "p-date-picker-7",
  "p-date-picker-8",
  "p-date-picker-9",
  "p-pagination-1",
  "p-pagination-2",
  "p-pagination-3",
  "p-scroll-area-1",
  "p-scroll-area-2",
  "p-scroll-area-3",
  "p-scroll-area-4",
  "p-scroll-area-5",
  "p-table-1",
  "p-table-2",
  "p-table-3",
  "p-table-4",
  "p-table-5",
  "p-table-6",
  "p-table-7",
  "p-table-8",
  "p-navigation-1",
  "p-navigation-2",
  "p-navigation-3",
  "p-radio-group-7",
  "p-radio-group-8",
  "p-radio-group-9",
  "p-tabs-1",
  "p-autocomplete-1",
  "p-autocomplete-10",
  "p-autocomplete-11",
  "p-autocomplete-12",
  "p-autocomplete-13",
  "p-autocomplete-14",
  "p-autocomplete-15",
  "p-autocomplete-16",
  "p-autocomplete-2",
  "p-autocomplete-3",
  "p-autocomplete-4",
  "p-autocomplete-5",
  "p-autocomplete-6",
  "p-autocomplete-7",
  "p-autocomplete-8",
  "p-autocomplete-9",
  "p-combobox-1",
  "p-combobox-10",
  "p-combobox-11",
  "p-combobox-12",
  "p-combobox-13",
  "p-combobox-14",
  "p-combobox-15",
  "p-combobox-16",
  "p-combobox-17",
  "p-combobox-18",
  "p-combobox-19",
  "p-combobox-2",
  "p-combobox-20",
  "p-combobox-3",
  "p-combobox-4",
  "p-combobox-5",
  "p-combobox-6",
  "p-combobox-7",
  "p-combobox-8",
  "p-combobox-9",
  "p-command-1",
  "p-command-2",
  "p-context-menu-1",
  "p-context-menu-2",
  "p-context-menu-3",
  "p-context-menu-4",
  "p-context-menu-5",
  "p-context-menu-6",
  "p-context-menu-7",
  "p-context-menu-8",
  "p-menu-1",
  "p-menu-2",
  "p-menu-3",
  "p-menu-4",
  "p-menu-5",
  "p-menu-6",
  "p-menu-7",
  "p-menu-8",
  "p-menu-9",
  "p-select-1",
  "p-select-10",
  "p-select-11",
  "p-select-12",
  "p-select-13",
  "p-select-14",
  "p-select-15",
  "p-select-16",
  "p-select-17",
  "p-select-18",
  "p-select-19",
  "p-select-2",
  "p-select-20",
  "p-select-21",
  "p-select-22",
  "p-select-23",
  "p-select-3",
  "p-select-4",
  "p-select-5",
  "p-select-6",
  "p-select-7",
  "p-select-8",
  "p-select-9",
  "p-toolbar-1",
] as const;

function particle(name: (typeof particleIds)[number]) {
  const category = name.replace(/^p-/, "").replace(/-\d+$/, "");
  const source = readFileSync(resolve(registryRoot, `default/particles/${name}.svelte`), "utf8");
  const catalogEntry = particleCatalogByName.get(name);
  if (!catalogEntry) throw new Error(`Missing COSS particle catalog entry for ${name}.`);
  const usesHugeicons = source.includes("HugeiconsIcon");
  return {
    categories: [category],
    dependencies: usesHugeicons ? ["@hugeicons/core-free-icons@4.3.0"] : [],
    description: `COSS ${category} example.`,
    files: [
      {
        path: `registry/default/particles/${name}.svelte`,
        type: "registry:block" as const,
      },
    ],
    name,
    registryDependencies: [
      "local:particle-metadata",
      ...catalogEntry.registryDependencies
        .map((dependency) => dependency.replace(/^@coss\//, ""))
        .filter((dependency) => componentRegistryNames.has(dependency))
        .map((dependency) => `local:${dependency}`),
      ...(usesHugeicons ? ["local:hugeicons-icon"] : []),
    ],
    type: "registry:block" as const,
  };
}

function d9Particle(
  name: (typeof particleIds)[number],
  options: {
    dependencies?: readonly string[];
    registryDependencies?: readonly string[];
  } = {},
) {
  const base = particle(name);
  return {
    ...base,
    dependencies: [...base.dependencies, ...(options.dependencies ?? [])],
    registryDependencies: [...base.registryDependencies, ...(options.registryDependencies ?? [])],
  };
}

const ssrSafeParticle = d9Particle;

export const registryParticles = defineRegistryItems([
  { ...particle("p-accordion-1"), name: "p-accordion-1" },
  { ...particle("p-accordion-2"), name: "p-accordion-2" },
  { ...particle("p-accordion-3"), name: "p-accordion-3" },
  { ...particle("p-accordion-4"), name: "p-accordion-4" },
  { ...particle("p-card-1"), name: "p-card-1" },
  { ...particle("p-card-10"), name: "p-card-10" },
  { ...particle("p-card-11"), name: "p-card-11" },
  { ...particle("p-card-2"), name: "p-card-2" },
  { ...particle("p-card-3"), name: "p-card-3" },
  { ...particle("p-card-4"), name: "p-card-4" },
  { ...particle("p-card-5"), name: "p-card-5" },
  { ...particle("p-card-6"), name: "p-card-6" },
  { ...particle("p-card-7"), name: "p-card-7" },
  { ...particle("p-card-8"), name: "p-card-8" },
  { ...particle("p-card-9"), name: "p-card-9" },
  { ...particle("p-collapsible-1"), name: "p-collapsible-1" },
  { ...particle("p-empty-1"), name: "p-empty-1" },
  { ...particle("p-frame-1"), name: "p-frame-1" },
  { ...particle("p-frame-2"), name: "p-frame-2" },
  { ...particle("p-frame-3"), name: "p-frame-3" },
  { ...particle("p-frame-4"), name: "p-frame-4" },
  { ...particle("p-separator-1"), name: "p-separator-1" },
  { ...particle("p-skeleton-1"), name: "p-skeleton-1" },
  { ...particle("p-skeleton-2"), name: "p-skeleton-2" },
  { ...particle("p-tabs-10"), name: "p-tabs-10" },
  { ...particle("p-tabs-11"), name: "p-tabs-11" },
  { ...particle("p-tabs-12"), name: "p-tabs-12" },
  { ...particle("p-tabs-13"), name: "p-tabs-13" },
  { ...particle("p-tabs-14"), name: "p-tabs-14" },
  { ...particle("p-tabs-15"), name: "p-tabs-15" },
  { ...particle("p-tabs-2"), name: "p-tabs-2" },
  { ...particle("p-tabs-3"), name: "p-tabs-3" },
  { ...particle("p-tabs-4"), name: "p-tabs-4" },
  { ...particle("p-tabs-5"), name: "p-tabs-5" },
  { ...particle("p-tabs-6"), name: "p-tabs-6" },
  { ...particle("p-tabs-7"), name: "p-tabs-7" },
  { ...particle("p-tabs-8"), name: "p-tabs-8" },
  { ...particle("p-tabs-9"), name: "p-tabs-9" },
  { ...particle("p-button-1"), name: "p-button-1" },
  { ...particle("p-button-10"), name: "p-button-10" },
  { ...particle("p-button-11"), name: "p-button-11" },
  { ...particle("p-button-12"), name: "p-button-12" },
  { ...particle("p-button-13"), name: "p-button-13" },
  { ...particle("p-button-14"), name: "p-button-14" },
  { ...particle("p-button-15"), name: "p-button-15" },
  { ...particle("p-button-16"), name: "p-button-16" },
  { ...particle("p-button-17"), name: "p-button-17" },
  { ...particle("p-button-18"), name: "p-button-18" },
  { ...particle("p-button-19"), name: "p-button-19" },
  { ...particle("p-button-2"), name: "p-button-2" },
  { ...particle("p-button-20"), name: "p-button-20" },
  { ...particle("p-button-21"), name: "p-button-21" },
  { ...particle("p-button-22"), name: "p-button-22" },
  { ...particle("p-button-23"), name: "p-button-23" },
  { ...particle("p-button-24"), name: "p-button-24" },
  { ...particle("p-button-26"), name: "p-button-26" },
  { ...particle("p-button-27"), name: "p-button-27" },
  { ...particle("p-button-28"), name: "p-button-28" },
  { ...particle("p-button-29"), name: "p-button-29" },
  { ...particle("p-button-3"), name: "p-button-3" },
  { ...particle("p-button-30"), name: "p-button-30" },
  { ...particle("p-button-31"), name: "p-button-31" },
  { ...particle("p-button-32"), name: "p-button-32" },
  { ...particle("p-button-33"), name: "p-button-33" },
  { ...particle("p-button-34"), name: "p-button-34" },
  { ...particle("p-button-35"), name: "p-button-35" },
  { ...particle("p-button-36"), name: "p-button-36" },
  { ...particle("p-button-37"), name: "p-button-37" },
  { ...particle("p-button-38"), name: "p-button-38" },
  { ...particle("p-button-39"), name: "p-button-39" },
  { ...particle("p-button-4"), name: "p-button-4" },
  { ...particle("p-button-40"), name: "p-button-40" },
  { ...particle("p-button-41"), name: "p-button-41" },
  { ...particle("p-button-5"), name: "p-button-5" },
  { ...particle("p-button-6"), name: "p-button-6" },
  { ...particle("p-button-7"), name: "p-button-7" },
  { ...particle("p-button-8"), name: "p-button-8" },
  { ...particle("p-button-9"), name: "p-button-9" },
  { ...particle("p-checkbox-1"), name: "p-checkbox-1" },
  { ...particle("p-checkbox-2"), name: "p-checkbox-2" },
  { ...particle("p-checkbox-3"), name: "p-checkbox-3" },
  { ...particle("p-checkbox-4"), name: "p-checkbox-4" },
  { ...particle("p-checkbox-5"), name: "p-checkbox-5" },
  { ...particle("p-checkbox-group-1"), name: "p-checkbox-group-1" },
  { ...particle("p-checkbox-group-2"), name: "p-checkbox-group-2" },
  { ...particle("p-checkbox-group-3"), name: "p-checkbox-group-3" },
  { ...particle("p-checkbox-group-4"), name: "p-checkbox-group-4" },
  { ...particle("p-checkbox-group-5"), name: "p-checkbox-group-5" },
  { ...particle("p-radio-group-1"), name: "p-radio-group-1" },
  { ...particle("p-radio-group-2"), name: "p-radio-group-2" },
  { ...particle("p-radio-group-3"), name: "p-radio-group-3" },
  { ...particle("p-radio-group-4"), name: "p-radio-group-4" },
  { ...particle("p-radio-group-5"), name: "p-radio-group-5" },
  { ...particle("p-radio-group-6"), name: "p-radio-group-6" },
  { ...particle("p-slider-1"), name: "p-slider-1" },
  { ...particle("p-slider-10"), name: "p-slider-10" },
  { ...particle("p-slider-11"), name: "p-slider-11" },
  { ...particle("p-slider-12"), name: "p-slider-12" },
  { ...particle("p-slider-13"), name: "p-slider-13" },
  { ...particle("p-slider-14"), name: "p-slider-14" },
  { ...particle("p-slider-15"), name: "p-slider-15" },
  { ...particle("p-slider-16"), name: "p-slider-16" },
  { ...particle("p-slider-17"), name: "p-slider-17" },
  { ...particle("p-slider-18"), name: "p-slider-18" },
  { ...particle("p-slider-19"), name: "p-slider-19" },
  { ...particle("p-slider-2"), name: "p-slider-2" },
  { ...particle("p-slider-20"), name: "p-slider-20" },
  { ...particle("p-slider-21"), name: "p-slider-21" },
  { ...particle("p-slider-22"), name: "p-slider-22" },
  { ...particle("p-slider-23"), name: "p-slider-23" },
  { ...particle("p-slider-3"), name: "p-slider-3" },
  { ...particle("p-slider-4"), name: "p-slider-4" },
  { ...particle("p-slider-5"), name: "p-slider-5" },
  { ...particle("p-slider-6"), name: "p-slider-6" },
  { ...particle("p-slider-7"), name: "p-slider-7" },
  { ...particle("p-slider-8"), name: "p-slider-8" },
  { ...particle("p-slider-9"), name: "p-slider-9" },
  { ...particle("p-switch-1"), name: "p-switch-1" },
  { ...particle("p-switch-2"), name: "p-switch-2" },
  { ...particle("p-switch-3"), name: "p-switch-3" },
  { ...particle("p-switch-4"), name: "p-switch-4" },
  { ...particle("p-switch-5"), name: "p-switch-5" },
  { ...particle("p-switch-6"), name: "p-switch-6" },
  { ...particle("p-switch-7"), name: "p-switch-7" },
  { ...particle("p-switch-8"), name: "p-switch-8" },
  { ...particle("p-switch-9"), name: "p-switch-9" },
  { ...particle("p-toggle-1"), name: "p-toggle-1" },
  { ...particle("p-toggle-2"), name: "p-toggle-2" },
  { ...particle("p-toggle-3"), name: "p-toggle-3" },
  { ...particle("p-toggle-4"), name: "p-toggle-4" },
  { ...particle("p-toggle-5"), name: "p-toggle-5" },
  { ...particle("p-toggle-6"), name: "p-toggle-6" },
  { ...particle("p-toggle-7"), name: "p-toggle-7" },
  { ...particle("p-toggle-8"), name: "p-toggle-8" },
  { ...particle("p-toggle-group-1"), name: "p-toggle-group-1" },
  { ...particle("p-toggle-group-2"), name: "p-toggle-group-2" },
  { ...particle("p-toggle-group-3"), name: "p-toggle-group-3" },
  { ...particle("p-toggle-group-4"), name: "p-toggle-group-4" },
  { ...particle("p-toggle-group-5"), name: "p-toggle-group-5" },
  { ...particle("p-toggle-group-6"), name: "p-toggle-group-6" },
  { ...particle("p-toggle-group-7"), name: "p-toggle-group-7" },
  { ...particle("p-toggle-group-8"), name: "p-toggle-group-8" },
  { ...particle("p-toggle-group-9"), name: "p-toggle-group-9" },
  { ...particle("p-alert-dialog-1"), name: "p-alert-dialog-1" },
  { ...particle("p-alert-dialog-2"), name: "p-alert-dialog-2" },
  { ...particle("p-dialog-1"), name: "p-dialog-1" },
  { ...particle("p-dialog-2"), name: "p-dialog-2" },
  { ...particle("p-dialog-3"), name: "p-dialog-3" },
  { ...particle("p-dialog-4"), name: "p-dialog-4" },
  { ...particle("p-dialog-5"), name: "p-dialog-5" },
  { ...particle("p-dialog-6"), name: "p-dialog-6" },
  { ...particle("p-drawer-1"), name: "p-drawer-1" },
  { ...particle("p-drawer-10"), name: "p-drawer-10" },
  { ...particle("p-drawer-11"), name: "p-drawer-11" },
  { ...particle("p-drawer-12"), name: "p-drawer-12" },
  { ...particle("p-drawer-13"), name: "p-drawer-13" },
  { ...particle("p-drawer-14"), name: "p-drawer-14" },
  { ...particle("p-drawer-2"), name: "p-drawer-2" },
  { ...particle("p-drawer-3"), name: "p-drawer-3" },
  { ...particle("p-drawer-4"), name: "p-drawer-4" },
  { ...particle("p-drawer-5"), name: "p-drawer-5" },
  { ...particle("p-drawer-6"), name: "p-drawer-6" },
  { ...particle("p-drawer-7"), name: "p-drawer-7" },
  { ...particle("p-drawer-8"), name: "p-drawer-8" },
  { ...particle("p-drawer-9"), name: "p-drawer-9" },
  { ...particle("p-popover-1"), name: "p-popover-1" },
  { ...particle("p-popover-2"), name: "p-popover-2" },
  { ...particle("p-popover-3"), name: "p-popover-3" },
  { ...particle("p-popover-4"), name: "p-popover-4" },
  { ...particle("p-preview-card-1"), name: "p-preview-card-1" },
  { ...particle("p-sheet-1"), name: "p-sheet-1" },
  { ...particle("p-sheet-2"), name: "p-sheet-2" },
  { ...particle("p-sheet-3"), name: "p-sheet-3" },
  { ...particle("p-tooltip-1"), name: "p-tooltip-1" },
  { ...particle("p-tooltip-2"), name: "p-tooltip-2" },
  { ...particle("p-tooltip-3"), name: "p-tooltip-3" },
  { ...particle("p-tooltip-4"), name: "p-tooltip-4" },
  { ...d9Particle("p-breadcrumb-1"), name: "p-breadcrumb-1" },
  { ...d9Particle("p-breadcrumb-2"), name: "p-breadcrumb-2" },
  { ...d9Particle("p-breadcrumb-3"), name: "p-breadcrumb-3" },
  { ...d9Particle("p-breadcrumb-4"), name: "p-breadcrumb-4" },
  { ...d9Particle("p-breadcrumb-5"), name: "p-breadcrumb-5" },
  { ...d9Particle("p-breadcrumb-6"), name: "p-breadcrumb-6" },
  { ...d9Particle("p-breadcrumb-7"), name: "p-breadcrumb-7" },
  { ...d9Particle("p-calendar-1"), name: "p-calendar-1" },
  { ...d9Particle("p-calendar-2"), name: "p-calendar-2" },
  { ...d9Particle("p-calendar-3"), name: "p-calendar-3" },
  { ...d9Particle("p-calendar-4"), name: "p-calendar-4" },
  { ...d9Particle("p-calendar-5"), name: "p-calendar-5" },
  { ...d9Particle("p-calendar-6"), name: "p-calendar-6" },
  { ...d9Particle("p-calendar-7"), name: "p-calendar-7" },
  { ...d9Particle("p-calendar-8"), name: "p-calendar-8" },
  { ...d9Particle("p-calendar-9"), name: "p-calendar-9" },
  { ...d9Particle("p-calendar-10"), name: "p-calendar-10" },
  { ...d9Particle("p-calendar-11"), name: "p-calendar-11" },
  { ...d9Particle("p-calendar-12"), name: "p-calendar-12" },
  { ...d9Particle("p-calendar-13"), name: "p-calendar-13" },
  { ...d9Particle("p-calendar-14"), name: "p-calendar-14" },
  { ...d9Particle("p-calendar-15"), name: "p-calendar-15" },
  { ...d9Particle("p-calendar-16"), name: "p-calendar-16" },
  { ...d9Particle("p-calendar-17"), name: "p-calendar-17" },
  { ...d9Particle("p-calendar-18"), name: "p-calendar-18" },
  { ...d9Particle("p-calendar-19"), name: "p-calendar-19" },
  { ...d9Particle("p-calendar-20"), name: "p-calendar-20" },
  { ...d9Particle("p-calendar-21"), name: "p-calendar-21" },
  { ...d9Particle("p-calendar-22"), name: "p-calendar-22" },
  { ...d9Particle("p-calendar-23"), name: "p-calendar-23" },
  { ...d9Particle("p-calendar-24"), name: "p-calendar-24" },
  { ...d9Particle("p-calendar-25"), name: "p-calendar-25" },
  {
    ...d9Particle("p-date-picker-1", { registryDependencies: ["local:date-format"] }),
    name: "p-date-picker-1",
  },
  { ...d9Particle("p-date-picker-2"), name: "p-date-picker-2" },
  {
    ...d9Particle("p-date-picker-3", { registryDependencies: ["local:date-format"] }),
    name: "p-date-picker-3",
  },
  {
    ...d9Particle("p-date-picker-4", { registryDependencies: ["local:date-format"] }),
    name: "p-date-picker-4",
  },
  { ...d9Particle("p-date-picker-5"), name: "p-date-picker-5" },
  {
    ...d9Particle("p-date-picker-6", { registryDependencies: ["local:date-format"] }),
    name: "p-date-picker-6",
  },
  { ...d9Particle("p-date-picker-7"), name: "p-date-picker-7" },
  {
    ...d9Particle("p-date-picker-8", { registryDependencies: ["local:date-format"] }),
    name: "p-date-picker-8",
  },
  { ...d9Particle("p-date-picker-9"), name: "p-date-picker-9" },
  { ...d9Particle("p-pagination-1"), name: "p-pagination-1" },
  { ...d9Particle("p-pagination-2"), name: "p-pagination-2" },
  { ...d9Particle("p-pagination-3"), name: "p-pagination-3" },
  { ...d9Particle("p-scroll-area-1"), name: "p-scroll-area-1" },
  { ...d9Particle("p-scroll-area-2"), name: "p-scroll-area-2" },
  { ...d9Particle("p-scroll-area-3"), name: "p-scroll-area-3" },
  { ...d9Particle("p-scroll-area-4"), name: "p-scroll-area-4" },
  { ...d9Particle("p-scroll-area-5"), name: "p-scroll-area-5" },
  { ...d9Particle("p-table-1"), name: "p-table-1" },
  { ...d9Particle("p-table-2"), name: "p-table-2" },
  {
    ...d9Particle("p-table-3", { dependencies: ["@tanstack/svelte-table@9.2.3"] }),
    name: "p-table-3",
  },
  {
    ...d9Particle("p-table-4", { dependencies: ["@tanstack/svelte-table@9.2.3"] }),
    name: "p-table-4",
  },
  { ...d9Particle("p-table-5"), name: "p-table-5" },
  {
    ...d9Particle("p-table-6", { dependencies: ["@tanstack/svelte-table@9.2.3"] }),
    name: "p-table-6",
  },
  { ...d9Particle("p-table-7"), name: "p-table-7" },
  {
    ...d9Particle("p-table-8", { dependencies: ["@tanstack/svelte-table@9.2.3"] }),
    name: "p-table-8",
  },
  {
    ...d9Particle("p-navigation-1", {
      registryDependencies: ["local:segmented-control"],
    }),
    name: "p-navigation-1",
  },
  {
    ...d9Particle("p-navigation-2", {
      registryDependencies: ["local:segmented-control"],
    }),
    name: "p-navigation-2",
  },
  {
    ...d9Particle("p-navigation-3", {
      registryDependencies: ["local:segmented-control"],
    }),
    name: "p-navigation-3",
  },
  {
    ...d9Particle("p-radio-group-7", {
      registryDependencies: ["local:segmented-control"],
    }),
    name: "p-radio-group-7",
  },
  {
    ...d9Particle("p-radio-group-8", {
      registryDependencies: ["local:segmented-control"],
    }),
    name: "p-radio-group-8",
  },
  {
    ...d9Particle("p-radio-group-9", {
      registryDependencies: ["local:segmented-control"],
    }),
    name: "p-radio-group-9",
  },
  { ...d9Particle("p-tabs-1"), name: "p-tabs-1" },
  { ...ssrSafeParticle("p-autocomplete-1"), name: "p-autocomplete-1" },
  { ...ssrSafeParticle("p-autocomplete-10"), name: "p-autocomplete-10" },
  { ...ssrSafeParticle("p-autocomplete-11"), name: "p-autocomplete-11" },
  { ...ssrSafeParticle("p-autocomplete-12"), name: "p-autocomplete-12" },
  { ...ssrSafeParticle("p-autocomplete-13"), name: "p-autocomplete-13" },
  { ...ssrSafeParticle("p-autocomplete-14"), name: "p-autocomplete-14" },
  { ...ssrSafeParticle("p-autocomplete-15"), name: "p-autocomplete-15" },
  { ...ssrSafeParticle("p-autocomplete-16"), name: "p-autocomplete-16" },
  { ...ssrSafeParticle("p-autocomplete-2"), name: "p-autocomplete-2" },
  { ...ssrSafeParticle("p-autocomplete-3"), name: "p-autocomplete-3" },
  { ...ssrSafeParticle("p-autocomplete-4"), name: "p-autocomplete-4" },
  { ...ssrSafeParticle("p-autocomplete-5"), name: "p-autocomplete-5" },
  { ...ssrSafeParticle("p-autocomplete-6"), name: "p-autocomplete-6" },
  { ...ssrSafeParticle("p-autocomplete-7"), name: "p-autocomplete-7" },
  { ...ssrSafeParticle("p-autocomplete-8"), name: "p-autocomplete-8" },
  { ...ssrSafeParticle("p-autocomplete-9"), name: "p-autocomplete-9" },
  { ...ssrSafeParticle("p-combobox-1"), name: "p-combobox-1" },
  { ...ssrSafeParticle("p-combobox-10"), name: "p-combobox-10" },
  { ...ssrSafeParticle("p-combobox-11"), name: "p-combobox-11" },
  { ...ssrSafeParticle("p-combobox-12"), name: "p-combobox-12" },
  { ...ssrSafeParticle("p-combobox-13"), name: "p-combobox-13" },
  { ...ssrSafeParticle("p-combobox-14"), name: "p-combobox-14" },
  { ...ssrSafeParticle("p-combobox-15"), name: "p-combobox-15" },
  { ...ssrSafeParticle("p-combobox-16"), name: "p-combobox-16" },
  { ...ssrSafeParticle("p-combobox-17"), name: "p-combobox-17" },
  { ...ssrSafeParticle("p-combobox-18"), name: "p-combobox-18" },
  { ...ssrSafeParticle("p-combobox-19"), name: "p-combobox-19" },
  { ...ssrSafeParticle("p-combobox-2"), name: "p-combobox-2" },
  { ...ssrSafeParticle("p-combobox-20"), name: "p-combobox-20" },
  { ...ssrSafeParticle("p-combobox-3"), name: "p-combobox-3" },
  { ...ssrSafeParticle("p-combobox-4"), name: "p-combobox-4" },
  { ...ssrSafeParticle("p-combobox-5"), name: "p-combobox-5" },
  { ...ssrSafeParticle("p-combobox-6"), name: "p-combobox-6" },
  { ...ssrSafeParticle("p-combobox-7"), name: "p-combobox-7" },
  { ...ssrSafeParticle("p-combobox-8"), name: "p-combobox-8" },
  { ...ssrSafeParticle("p-combobox-9"), name: "p-combobox-9" },
  { ...ssrSafeParticle("p-command-1"), name: "p-command-1" },
  { ...ssrSafeParticle("p-command-2"), name: "p-command-2" },
  { ...ssrSafeParticle("p-context-menu-1"), name: "p-context-menu-1" },
  { ...ssrSafeParticle("p-context-menu-2"), name: "p-context-menu-2" },
  { ...ssrSafeParticle("p-context-menu-3"), name: "p-context-menu-3" },
  { ...ssrSafeParticle("p-context-menu-4"), name: "p-context-menu-4" },
  { ...ssrSafeParticle("p-context-menu-5"), name: "p-context-menu-5" },
  { ...ssrSafeParticle("p-context-menu-6"), name: "p-context-menu-6" },
  { ...ssrSafeParticle("p-context-menu-7"), name: "p-context-menu-7" },
  { ...ssrSafeParticle("p-context-menu-8"), name: "p-context-menu-8" },
  { ...ssrSafeParticle("p-menu-1"), name: "p-menu-1" },
  { ...ssrSafeParticle("p-menu-2"), name: "p-menu-2" },
  { ...ssrSafeParticle("p-menu-3"), name: "p-menu-3" },
  { ...ssrSafeParticle("p-menu-4"), name: "p-menu-4" },
  { ...ssrSafeParticle("p-menu-5"), name: "p-menu-5" },
  { ...ssrSafeParticle("p-menu-6"), name: "p-menu-6" },
  { ...ssrSafeParticle("p-menu-7"), name: "p-menu-7" },
  { ...ssrSafeParticle("p-menu-8"), name: "p-menu-8" },
  { ...ssrSafeParticle("p-menu-9"), name: "p-menu-9" },
  { ...ssrSafeParticle("p-select-1"), name: "p-select-1" },
  { ...ssrSafeParticle("p-select-10"), name: "p-select-10" },
  { ...ssrSafeParticle("p-select-11"), name: "p-select-11" },
  { ...ssrSafeParticle("p-select-12"), name: "p-select-12" },
  { ...ssrSafeParticle("p-select-13"), name: "p-select-13" },
  { ...ssrSafeParticle("p-select-14"), name: "p-select-14" },
  { ...ssrSafeParticle("p-select-15"), name: "p-select-15" },
  { ...ssrSafeParticle("p-select-16"), name: "p-select-16" },
  { ...ssrSafeParticle("p-select-17"), name: "p-select-17" },
  { ...ssrSafeParticle("p-select-18"), name: "p-select-18" },
  { ...ssrSafeParticle("p-select-19"), name: "p-select-19" },
  { ...ssrSafeParticle("p-select-2"), name: "p-select-2" },
  { ...ssrSafeParticle("p-select-20"), name: "p-select-20" },
  { ...ssrSafeParticle("p-select-21"), name: "p-select-21" },
  { ...ssrSafeParticle("p-select-22"), name: "p-select-22" },
  { ...ssrSafeParticle("p-select-23"), name: "p-select-23" },
  { ...ssrSafeParticle("p-select-3"), name: "p-select-3" },
  { ...ssrSafeParticle("p-select-4"), name: "p-select-4" },
  { ...ssrSafeParticle("p-select-5"), name: "p-select-5" },
  { ...ssrSafeParticle("p-select-6"), name: "p-select-6" },
  { ...ssrSafeParticle("p-select-7"), name: "p-select-7" },
  { ...ssrSafeParticle("p-select-8"), name: "p-select-8" },
  { ...ssrSafeParticle("p-select-9"), name: "p-select-9" },
  { ...ssrSafeParticle("p-toolbar-1"), name: "p-toolbar-1" },
]);
