import { defineRegistryItems } from "./registry.js";

const particleIds = [
  "p-accordion-1",
  "p-accordion-2",
  "p-accordion-3",
  "p-accordion-4",
  "p-card-1",
  "p-card-10",
  "p-card-11",
  "p-card-2",
  "p-card-3",
  "p-card-4",
  "p-card-5",
  "p-card-6",
  "p-card-7",
  "p-card-8",
  "p-card-9",
  "p-collapsible-1",
  "p-empty-1",
  "p-frame-1",
  "p-frame-2",
  "p-frame-3",
  "p-frame-4",
  "p-separator-1",
  "p-skeleton-1",
  "p-skeleton-2",
  "p-tabs-10",
  "p-tabs-11",
  "p-tabs-12",
  "p-tabs-13",
  "p-tabs-14",
  "p-tabs-15",
  "p-tabs-2",
  "p-tabs-3",
  "p-tabs-4",
  "p-tabs-5",
  "p-tabs-6",
  "p-tabs-7",
  "p-tabs-8",
  "p-tabs-9",
  "p-button-1",
  "p-button-10",
  "p-button-11",
  "p-button-12",
  "p-button-13",
  "p-button-14",
  "p-button-15",
  "p-button-16",
  "p-button-17",
  "p-button-18",
  "p-button-19",
  "p-button-2",
  "p-button-20",
  "p-button-21",
  "p-button-22",
  "p-button-23",
  "p-button-24",
  "p-button-26",
  "p-button-27",
  "p-button-28",
  "p-button-29",
  "p-button-3",
  "p-button-30",
  "p-button-31",
  "p-button-32",
  "p-button-33",
  "p-button-34",
  "p-button-35",
  "p-button-36",
  "p-button-37",
  "p-button-38",
  "p-button-39",
  "p-button-4",
  "p-button-40",
  "p-button-41",
  "p-button-5",
  "p-button-6",
  "p-button-7",
  "p-button-8",
  "p-button-9",
  "p-checkbox-1",
  "p-checkbox-2",
  "p-checkbox-3",
  "p-checkbox-4",
  "p-checkbox-5",
  "p-checkbox-group-1",
  "p-checkbox-group-2",
  "p-checkbox-group-3",
  "p-checkbox-group-4",
  "p-checkbox-group-5",
  "p-radio-group-1",
  "p-radio-group-2",
  "p-radio-group-3",
  "p-radio-group-4",
  "p-radio-group-5",
  "p-radio-group-6",
  "p-slider-1",
  "p-slider-10",
  "p-slider-11",
  "p-slider-12",
  "p-slider-13",
  "p-slider-14",
  "p-slider-15",
  "p-slider-16",
  "p-slider-17",
  "p-slider-18",
  "p-slider-19",
  "p-slider-2",
  "p-slider-20",
  "p-slider-21",
  "p-slider-22",
  "p-slider-23",
  "p-slider-3",
  "p-slider-4",
  "p-slider-5",
  "p-slider-6",
  "p-slider-7",
  "p-slider-8",
  "p-slider-9",
  "p-switch-1",
  "p-switch-2",
  "p-switch-3",
  "p-switch-4",
  "p-switch-5",
  "p-switch-6",
  "p-switch-7",
  "p-switch-8",
  "p-switch-9",
  "p-toggle-1",
  "p-toggle-2",
  "p-toggle-3",
  "p-toggle-4",
  "p-toggle-5",
  "p-toggle-6",
  "p-toggle-7",
  "p-toggle-8",
  "p-toggle-group-1",
  "p-toggle-group-2",
  "p-toggle-group-3",
  "p-toggle-group-4",
  "p-toggle-group-5",
  "p-toggle-group-6",
  "p-toggle-group-7",
  "p-toggle-group-8",
  "p-toggle-group-9",
] as const;

function particle(name: (typeof particleIds)[number]) {
  const category = name.replace(/^p-/, "").replace(/-\d+$/, "");
  return {
    categories: [category],
    dependencies: ["@coss-sv/ui", "@hugeicons/core-free-icons@4.3.0", "@hugeicons/svelte@1.1.5"],
    description: `COSS ${category} example.`,
    files: [
      {
        path: `registry/default/particles/${name}.svelte`,
        type: "registry:block" as const,
      },
    ],
    name,
    registryDependencies: ["local:particle-metadata"],
    type: "registry:block" as const,
  };
}

export const registryParticles = defineRegistryItems([
  { ...particle("p-accordion-1"), name: "p-accordion-1" },
  { ...particle("p-accordion-2"), name: "p-accordion-2" },
  { ...particle("p-accordion-3"), name: "p-accordion-3" },
  { ...particle("p-accordion-4"), name: "p-accordion-4" },
  { ...particle("p-card-1"), name: "p-card-1" },
  { ...particle("p-card-10"), name: "p-card-10" },
  { ...particle("p-card-11"), name: "p-card-11" },
  { ...particle("p-card-2"), name: "p-card-2" },
  { ...particle("p-card-3"), name: "p-card-3" },
  { ...particle("p-card-4"), name: "p-card-4" },
  { ...particle("p-card-5"), name: "p-card-5" },
  { ...particle("p-card-6"), name: "p-card-6" },
  { ...particle("p-card-7"), name: "p-card-7" },
  { ...particle("p-card-8"), name: "p-card-8" },
  { ...particle("p-card-9"), name: "p-card-9" },
  { ...particle("p-collapsible-1"), name: "p-collapsible-1" },
  { ...particle("p-empty-1"), name: "p-empty-1" },
  { ...particle("p-frame-1"), name: "p-frame-1" },
  { ...particle("p-frame-2"), name: "p-frame-2" },
  { ...particle("p-frame-3"), name: "p-frame-3" },
  { ...particle("p-frame-4"), name: "p-frame-4" },
  { ...particle("p-separator-1"), name: "p-separator-1" },
  { ...particle("p-skeleton-1"), name: "p-skeleton-1" },
  { ...particle("p-skeleton-2"), name: "p-skeleton-2" },
  { ...particle("p-tabs-10"), name: "p-tabs-10" },
  { ...particle("p-tabs-11"), name: "p-tabs-11" },
  { ...particle("p-tabs-12"), name: "p-tabs-12" },
  { ...particle("p-tabs-13"), name: "p-tabs-13" },
  { ...particle("p-tabs-14"), name: "p-tabs-14" },
  { ...particle("p-tabs-15"), name: "p-tabs-15" },
  { ...particle("p-tabs-2"), name: "p-tabs-2" },
  { ...particle("p-tabs-3"), name: "p-tabs-3" },
  { ...particle("p-tabs-4"), name: "p-tabs-4" },
  { ...particle("p-tabs-5"), name: "p-tabs-5" },
  { ...particle("p-tabs-6"), name: "p-tabs-6" },
  { ...particle("p-tabs-7"), name: "p-tabs-7" },
  { ...particle("p-tabs-8"), name: "p-tabs-8" },
  { ...particle("p-tabs-9"), name: "p-tabs-9" },
  { ...particle("p-button-1"), name: "p-button-1" },
  { ...particle("p-button-10"), name: "p-button-10" },
  { ...particle("p-button-11"), name: "p-button-11" },
  { ...particle("p-button-12"), name: "p-button-12" },
  { ...particle("p-button-13"), name: "p-button-13" },
  { ...particle("p-button-14"), name: "p-button-14" },
  { ...particle("p-button-15"), name: "p-button-15" },
  { ...particle("p-button-16"), name: "p-button-16" },
  { ...particle("p-button-17"), name: "p-button-17" },
  { ...particle("p-button-18"), name: "p-button-18" },
  { ...particle("p-button-19"), name: "p-button-19" },
  { ...particle("p-button-2"), name: "p-button-2" },
  { ...particle("p-button-20"), name: "p-button-20" },
  { ...particle("p-button-21"), name: "p-button-21" },
  { ...particle("p-button-22"), name: "p-button-22" },
  { ...particle("p-button-23"), name: "p-button-23" },
  { ...particle("p-button-24"), name: "p-button-24" },
  { ...particle("p-button-26"), name: "p-button-26" },
  { ...particle("p-button-27"), name: "p-button-27" },
  { ...particle("p-button-28"), name: "p-button-28" },
  { ...particle("p-button-29"), name: "p-button-29" },
  { ...particle("p-button-3"), name: "p-button-3" },
  { ...particle("p-button-30"), name: "p-button-30" },
  { ...particle("p-button-31"), name: "p-button-31" },
  { ...particle("p-button-32"), name: "p-button-32" },
  { ...particle("p-button-33"), name: "p-button-33" },
  { ...particle("p-button-34"), name: "p-button-34" },
  { ...particle("p-button-35"), name: "p-button-35" },
  { ...particle("p-button-36"), name: "p-button-36" },
  { ...particle("p-button-37"), name: "p-button-37" },
  { ...particle("p-button-38"), name: "p-button-38" },
  { ...particle("p-button-39"), name: "p-button-39" },
  { ...particle("p-button-4"), name: "p-button-4" },
  { ...particle("p-button-40"), name: "p-button-40" },
  { ...particle("p-button-41"), name: "p-button-41" },
  { ...particle("p-button-5"), name: "p-button-5" },
  { ...particle("p-button-6"), name: "p-button-6" },
  { ...particle("p-button-7"), name: "p-button-7" },
  { ...particle("p-button-8"), name: "p-button-8" },
  { ...particle("p-button-9"), name: "p-button-9" },
  { ...particle("p-checkbox-1"), name: "p-checkbox-1" },
  { ...particle("p-checkbox-2"), name: "p-checkbox-2" },
  { ...particle("p-checkbox-3"), name: "p-checkbox-3" },
  { ...particle("p-checkbox-4"), name: "p-checkbox-4" },
  { ...particle("p-checkbox-5"), name: "p-checkbox-5" },
  { ...particle("p-checkbox-group-1"), name: "p-checkbox-group-1" },
  { ...particle("p-checkbox-group-2"), name: "p-checkbox-group-2" },
  { ...particle("p-checkbox-group-3"), name: "p-checkbox-group-3" },
  { ...particle("p-checkbox-group-4"), name: "p-checkbox-group-4" },
  { ...particle("p-checkbox-group-5"), name: "p-checkbox-group-5" },
  { ...particle("p-radio-group-1"), name: "p-radio-group-1" },
  { ...particle("p-radio-group-2"), name: "p-radio-group-2" },
  { ...particle("p-radio-group-3"), name: "p-radio-group-3" },
  { ...particle("p-radio-group-4"), name: "p-radio-group-4" },
  { ...particle("p-radio-group-5"), name: "p-radio-group-5" },
  { ...particle("p-radio-group-6"), name: "p-radio-group-6" },
  { ...particle("p-slider-1"), name: "p-slider-1" },
  { ...particle("p-slider-10"), name: "p-slider-10" },
  { ...particle("p-slider-11"), name: "p-slider-11" },
  { ...particle("p-slider-12"), name: "p-slider-12" },
  { ...particle("p-slider-13"), name: "p-slider-13" },
  { ...particle("p-slider-14"), name: "p-slider-14" },
  { ...particle("p-slider-15"), name: "p-slider-15" },
  { ...particle("p-slider-16"), name: "p-slider-16" },
  { ...particle("p-slider-17"), name: "p-slider-17" },
  { ...particle("p-slider-18"), name: "p-slider-18" },
  { ...particle("p-slider-19"), name: "p-slider-19" },
  { ...particle("p-slider-2"), name: "p-slider-2" },
  { ...particle("p-slider-20"), name: "p-slider-20" },
  { ...particle("p-slider-21"), name: "p-slider-21" },
  { ...particle("p-slider-22"), name: "p-slider-22" },
  { ...particle("p-slider-23"), name: "p-slider-23" },
  { ...particle("p-slider-3"), name: "p-slider-3" },
  { ...particle("p-slider-4"), name: "p-slider-4" },
  { ...particle("p-slider-5"), name: "p-slider-5" },
  { ...particle("p-slider-6"), name: "p-slider-6" },
  { ...particle("p-slider-7"), name: "p-slider-7" },
  { ...particle("p-slider-8"), name: "p-slider-8" },
  { ...particle("p-slider-9"), name: "p-slider-9" },
  { ...particle("p-switch-1"), name: "p-switch-1" },
  { ...particle("p-switch-2"), name: "p-switch-2" },
  { ...particle("p-switch-3"), name: "p-switch-3" },
  { ...particle("p-switch-4"), name: "p-switch-4" },
  { ...particle("p-switch-5"), name: "p-switch-5" },
  { ...particle("p-switch-6"), name: "p-switch-6" },
  { ...particle("p-switch-7"), name: "p-switch-7" },
  { ...particle("p-switch-8"), name: "p-switch-8" },
  { ...particle("p-switch-9"), name: "p-switch-9" },
  { ...particle("p-toggle-1"), name: "p-toggle-1" },
  { ...particle("p-toggle-2"), name: "p-toggle-2" },
  { ...particle("p-toggle-3"), name: "p-toggle-3" },
  { ...particle("p-toggle-4"), name: "p-toggle-4" },
  { ...particle("p-toggle-5"), name: "p-toggle-5" },
  { ...particle("p-toggle-6"), name: "p-toggle-6" },
  { ...particle("p-toggle-7"), name: "p-toggle-7" },
  { ...particle("p-toggle-8"), name: "p-toggle-8" },
  { ...particle("p-toggle-group-1"), name: "p-toggle-group-1" },
  { ...particle("p-toggle-group-2"), name: "p-toggle-group-2" },
  { ...particle("p-toggle-group-3"), name: "p-toggle-group-3" },
  { ...particle("p-toggle-group-4"), name: "p-toggle-group-4" },
  { ...particle("p-toggle-group-5"), name: "p-toggle-group-5" },
  { ...particle("p-toggle-group-6"), name: "p-toggle-group-6" },
  { ...particle("p-toggle-group-7"), name: "p-toggle-group-7" },
  { ...particle("p-toggle-group-8"), name: "p-toggle-group-8" },
  { ...particle("p-toggle-group-9"), name: "p-toggle-group-9" },
]);
