import { defineRegistryItems } from "./registry.js";

function uiFiles(component: string, files: string[]) {
  return files.map((file) => ({
    path: `../../packages/ui/src/components/ui/${component}/${file}`,
    type: "registry:ui" as const,
  }));
}

export const registryUi = defineRegistryItems([
  {
    name: "accordion",
    type: "registry:ui",
    description: "Organizes content into expandable sections.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("accordion", [
      "accordion-root.svelte",
      "accordion-item.svelte",
      "accordion-header.svelte",
      "accordion-trigger.svelte",
      "accordion-panel.svelte",
      "index.ts",
    ]),
  },
  {
    name: "alert-dialog",
    type: "registry:ui",
    description: "Asks the user to confirm or cancel a consequential action.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: ["local:dialog"],
    files: uiFiles("alert-dialog", [
      "alert-dialog-backdrop.svelte",
      "alert-dialog-close.svelte",
      "alert-dialog-description.svelte",
      "alert-dialog-footer.svelte",
      "alert-dialog-header.svelte",
      "alert-dialog-popup.svelte",
      "alert-dialog-title.svelte",
      "alert-dialog-trigger.svelte",
      "alert-dialog-viewport.svelte",
      "index.ts",
    ]),
  },
  {
    name: "alert",
    type: "registry:ui",
    description: "Displays a message with an optional action.",
    dependencies: [],
    registryDependencies: [],
    files: uiFiles("alert", [
      "alert.svelte",
      "alert-action.svelte",
      "alert-description.svelte",
      "alert-title.svelte",
      "index.ts",
    ]),
  },
  {
    name: "autocomplete",
    type: "registry:ui",
    description: "Suggests and filters values as a user types.",
    dependencies: [
      "@hugeicons/core-free-icons@4.3.0",
      "@hugeicons/svelte@1.1.5",
      "@shardsui/svelte@0.1.0-beta.0",
    ],
    registryDependencies: [],
    files: uiFiles("autocomplete", [
      "autocomplete-clear.svelte",
      "autocomplete-empty.svelte",
      "autocomplete-group-label.svelte",
      "autocomplete-group.svelte",
      "autocomplete-input.svelte",
      "autocomplete-item.svelte",
      "autocomplete-list.svelte",
      "autocomplete-parts.svelte",
      "autocomplete-popup.svelte",
      "autocomplete-row.svelte",
      "autocomplete-separator.svelte",
      "autocomplete-status.svelte",
      "autocomplete-trigger.svelte",
      "index.ts",
    ]),
  },
  {
    name: "badge",
    type: "registry:ui",
    description: "Labels a status, category, or count.",
    dependencies: [],
    registryDependencies: [],
    files: uiFiles("badge", ["badge.svelte", "index.ts"]),
  },
  {
    name: "avatar",
    type: "registry:ui",
    description: "Displays an image or fallback for a person or entity.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("avatar", [
      "avatar-root.svelte",
      "avatar-image.svelte",
      "avatar-fallback.svelte",
      "index.ts",
    ]),
  },
  {
    name: "button",
    type: "registry:ui",
    description: "Triggers an action or navigates to another page.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: ["local:spinner"],
    files: uiFiles("button", ["button.svelte", "index.ts"]),
  },
  {
    name: "calendar",
    type: "registry:ui",
    description: "Displays and selects dates in one or more calendar months.",
    dependencies: ["@hugeicons/core-free-icons@4.3.0"],
    registryDependencies: ["local:hugeicons-icon"],
    files: uiFiles("calendar", [
      "calendar.svelte",
      "calendar.types.ts",
      "calendar.utils.ts",
      "index.ts",
    ]),
  },
  {
    name: "breadcrumb",
    type: "registry:ui",
    description: "Shows the current page within a hierarchy.",
    dependencies: ["@hugeicons/core-free-icons@4.3.0"],
    registryDependencies: ["local:hugeicons-icon"],
    files: uiFiles("breadcrumb", [
      "breadcrumb.svelte",
      "breadcrumb-ellipsis.svelte",
      "breadcrumb-item.svelte",
      "breadcrumb-link.svelte",
      "breadcrumb-list.svelte",
      "breadcrumb-page.svelte",
      "breadcrumb-separator.svelte",
      "index.ts",
    ]),
  },
  {
    name: "card",
    type: "registry:ui",
    description: "Groups related content and actions.",
    dependencies: [],
    registryDependencies: [],
    files: uiFiles("card", [
      "card.svelte",
      "card-action.svelte",
      "card-description.svelte",
      "card-footer.svelte",
      "card-frame.svelte",
      "card-frame-action.svelte",
      "card-frame-description.svelte",
      "card-frame-footer.svelte",
      "card-frame-header.svelte",
      "card-frame-title.svelte",
      "card-header.svelte",
      "card-panel.svelte",
      "card-part.svelte",
      "card-title.svelte",
      "index.ts",
    ]),
  },
  {
    name: "checkbox",
    type: "registry:ui",
    description: "Lets a user select or clear an option.",
    dependencies: ["@hugeicons/core-free-icons@4.3.0", "@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: ["local:hugeicons-icon"],
    files: uiFiles("checkbox", ["checkbox.svelte", "index.ts"]),
  },
  {
    name: "checkbox-group",
    type: "registry:ui",
    description: "Coordinates selection across a group of checkboxes.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: ["local:checkbox"],
    files: uiFiles("checkbox-group", [
      "checkbox-group-root.svelte",
      "checkbox-group-item.svelte",
      "change-event-details.ts",
      "context.ts",
      "index.ts",
    ]),
  },
  {
    name: "collapsible",
    type: "registry:ui",
    description: "Shows and hides a panel from a trigger.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: ["local:button"],
    files: uiFiles("collapsible", [
      "collapsible-root.svelte",
      "collapsible-provider.svelte",
      "collapsible-trigger.svelte",
      "collapsible-panel.svelte",
      "context.ts",
      "event-preventable.ts",
      "index.ts",
    ]),
  },
  {
    name: "combobox",
    type: "registry:ui",
    description: "Selects one or more values from a filterable collection.",
    dependencies: [
      "@hugeicons/core-free-icons@4.3.0",
      "@hugeicons/svelte@1.1.5",
      "@shardsui/svelte@0.1.0-beta.0",
    ],
    registryDependencies: [],
    files: uiFiles("combobox", [
      "combobox-chip-remove.svelte",
      "combobox-chip.svelte",
      "combobox-chips-input.svelte",
      "combobox-chips.svelte",
      "combobox-clear.svelte",
      "combobox-empty.svelte",
      "combobox-group-label.svelte",
      "combobox-group.svelte",
      "combobox-input.svelte",
      "combobox-item.svelte",
      "combobox-list.svelte",
      "combobox-parts.svelte",
      "combobox-popup.svelte",
      "combobox-root.svelte",
      "combobox-row.svelte",
      "combobox-separator.svelte",
      "combobox-status.svelte",
      "combobox-trigger.svelte",
      "combobox-value.svelte",
      "context.svelte.ts",
      "index.ts",
    ]),
  },
  {
    name: "command",
    type: "registry:ui",
    description: "Presents searchable commands in a panel or dialog.",
    dependencies: [
      "@hugeicons/core-free-icons@4.3.0",
      "@hugeicons/svelte@1.1.5",
      "@shardsui/svelte@0.1.0-beta.0",
    ],
    registryDependencies: [],
    files: uiFiles("command", [
      "command-dialog-backdrop.svelte",
      "command-dialog-popup.svelte",
      "command-dialog-trigger.svelte",
      "command-dialog-viewport.svelte",
      "command-empty.svelte",
      "command-footer.svelte",
      "command-group-label.svelte",
      "command-group.svelte",
      "command-input.svelte",
      "command-item.svelte",
      "command-list.svelte",
      "command-panel.svelte",
      "command-part.svelte",
      "command-root.svelte",
      "command-separator.svelte",
      "command-shortcut.svelte",
      "index.ts",
    ]),
  },
  {
    name: "context-menu",
    type: "registry:ui",
    description: "Opens a menu at the pointer position for contextual actions.",
    dependencies: ["@hugeicons/core-free-icons@4.3.0", "@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: ["local:hugeicons-icon"],
    files: uiFiles("context-menu", [
      "context-menu-checkbox-item.svelte",
      "context-menu-group-label.svelte",
      "context-menu-group.svelte",
      "context-menu-id-provider.svelte",
      "context-menu-item.svelte",
      "context-menu-link-item.svelte",
      "context-menu-popup.svelte",
      "context-menu-radio-group.svelte",
      "context-menu-radio-item.svelte",
      "context-menu-root.svelte",
      "context-menu-separator.svelte",
      "context-menu-shortcut.svelte",
      "context-menu-sub-popup.svelte",
      "context-menu-sub-trigger.svelte",
      "context-menu-sub.svelte",
      "context-menu-trigger.svelte",
      "context-menu.types.ts",
      "id-context.svelte.ts",
      "index.ts",
    ]),
  },
  {
    name: "dialog",
    type: "registry:ui",
    description: "Displays focused content in a modal or non-modal overlay.",
    dependencies: ["@hugeicons/core-free-icons@4.3.0", "@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: ["local:button", "local:hugeicons-icon", "local:scroll-area"],
    files: uiFiles("dialog", [
      "dialog-backdrop.svelte",
      "dialog-close.svelte",
      "dialog-description.svelte",
      "dialog-footer.svelte",
      "dialog-header.svelte",
      "dialog-panel.svelte",
      "dialog-part.svelte",
      "dialog-popup.svelte",
      "dialog-title.svelte",
      "dialog-trigger.svelte",
      "dialog-viewport.svelte",
      "index.ts",
    ]),
  },
  {
    name: "drawer",
    type: "registry:ui",
    description: "Presents draggable overlay content from an edge of the viewport.",
    dependencies: ["@hugeicons/core-free-icons@4.3.0", "@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [
      "local:button",
      "local:dialog",
      "local:hugeicons-icon",
      "local:scroll-area",
    ],
    files: uiFiles("drawer", [
      "context.ts",
      "drawer-backdrop.svelte",
      "drawer-bar.svelte",
      "drawer-close.svelte",
      "drawer-content.svelte",
      "drawer-description.svelte",
      "drawer-footer.svelte",
      "drawer-header.svelte",
      "drawer-menu-checkbox-item.svelte",
      "drawer-menu-group-label.svelte",
      "drawer-menu-group.svelte",
      "drawer-menu-item.svelte",
      "drawer-menu-radio-group.svelte",
      "drawer-menu-radio-item.svelte",
      "drawer-menu-separator.svelte",
      "drawer-menu-trigger.svelte",
      "drawer-menu.svelte",
      "drawer-panel-content.svelte",
      "drawer-panel.svelte",
      "drawer-part.svelte",
      "drawer-popup.svelte",
      "drawer-root.svelte",
      "drawer-swipe-area.svelte",
      "drawer-title.svelte",
      "drawer-trigger.svelte",
      "drawer-viewport.svelte",
      "index.ts",
    ]),
  },
  {
    name: "empty",
    type: "registry:ui",
    description: "Explains an empty state and its next actions.",
    dependencies: [],
    registryDependencies: [],
    files: uiFiles("empty", [
      "empty.svelte",
      "empty-content.svelte",
      "empty-description.svelte",
      "empty-header.svelte",
      "empty-media.svelte",
      "empty-part.svelte",
      "empty-title.svelte",
      "index.ts",
    ]),
  },
  {
    name: "frame",
    type: "registry:ui",
    description: "Frames related content with a header and footer.",
    dependencies: [],
    registryDependencies: [],
    files: uiFiles("frame", [
      "frame.svelte",
      "frame-description.svelte",
      "frame-footer.svelte",
      "frame-header.svelte",
      "frame-panel.svelte",
      "frame-title.svelte",
      "index.ts",
    ]),
  },
  {
    name: "field",
    type: "registry:ui",
    description: "Connects a form control with its label, help text, and errors.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: ["local:fieldset"],
    files: uiFiles("field", [
      "field-root.svelte",
      "field-label.svelte",
      "field-item.svelte",
      "field-description.svelte",
      "field-error.svelte",
      "field-relationship-provider.svelte",
      "relationship-context.svelte.ts",
      "index.ts",
    ]),
  },
  {
    name: "fieldset",
    type: "registry:ui",
    description: "Groups related form fields under a shared legend.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("fieldset", [
      "fieldset-root.svelte",
      "fieldset-legend.svelte",
      "context.svelte.ts",
      "index.ts",
    ]),
  },
  {
    name: "form",
    type: "registry:ui",
    description: "Coordinates form submission and field errors.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("form", ["form.svelte", "index.ts"]),
  },
  {
    name: "group",
    type: "registry:ui",
    description: "Joins related controls into one visual group.",
    dependencies: [],
    registryDependencies: ["local:separator"],
    files: uiFiles("group", [
      "group-root.svelte",
      "group-separator.svelte",
      "group-text.svelte",
      "group-styles.ts",
      "index.ts",
    ]),
  },
  {
    name: "input",
    type: "registry:ui",
    description: "Collects a single line of user input.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("input", ["input.svelte", "index.ts"]),
  },
  {
    name: "input-group",
    type: "registry:ui",
    description: "Combines an input or textarea with inline and block addons.",
    dependencies: [],
    registryDependencies: ["local:input", "local:textarea"],
    files: uiFiles("input-group", [
      "input-group-root.svelte",
      "input-group-input.svelte",
      "input-group-textarea.svelte",
      "input-group-addon.svelte",
      "input-group-text.svelte",
      "input-group-styles.ts",
      "index.ts",
    ]),
  },
  {
    name: "kbd",
    type: "registry:ui",
    description: "Represents keyboard input and shortcuts.",
    dependencies: [],
    registryDependencies: [],
    files: uiFiles("kbd", ["kbd.svelte", "kbd-group.svelte", "index.ts"]),
  },
  {
    name: "label",
    type: "registry:ui",
    description: "Labels an associated form control.",
    dependencies: [],
    registryDependencies: [],
    files: uiFiles("label", ["label.svelte", "index.ts"]),
  },
  {
    name: "menu",
    type: "registry:ui",
    description: "Presents actions, links, and nested choices from a trigger.",
    dependencies: ["@hugeicons/core-free-icons@4.3.0", "@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: ["local:hugeicons-icon"],
    files: uiFiles("menu", [
      "menu-checkbox-item.svelte",
      "menu-group-label.svelte",
      "menu-group.svelte",
      "menu-item.svelte",
      "menu-link-item.svelte",
      "menu-popup.svelte",
      "menu-radio-group.svelte",
      "menu-radio-item.svelte",
      "menu-root.svelte",
      "menu-separator.svelte",
      "menu-shortcut.svelte",
      "menu-sub-popup.svelte",
      "menu-sub-trigger.svelte",
      "menu-sub.svelte",
      "menu-trigger.svelte",
      "menu.types.ts",
      "index.ts",
    ]),
  },
  {
    name: "meter",
    type: "registry:ui",
    description: "Shows a scalar measurement within a known range.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("meter", [
      "meter-root.svelte",
      "meter-label.svelte",
      "meter-track.svelte",
      "meter-indicator.svelte",
      "meter-value.svelte",
      "index.ts",
    ]),
  },
  {
    name: "number-field",
    type: "registry:ui",
    description: "Collects and adjusts a locale-aware numeric value.",
    dependencies: ["@hugeicons/core-free-icons@4.3.0", "@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: ["local:hugeicons-icon", "local:label"],
    files: uiFiles("number-field", [
      "context.ts",
      "cursor-grow-icon.svelte",
      "number-field-decrement.svelte",
      "number-field-group.svelte",
      "number-field-increment.svelte",
      "number-field-input.svelte",
      "number-field-machine.ts",
      "number-field-root.svelte",
      "number-field-scrub-area.svelte",
      "number-field-step-button.svelte",
      "index.ts",
    ]),
  },
  {
    name: "otp-field",
    type: "registry:ui",
    description: "Collects a one-time code across a group of input slots.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: ["local:field", "local:separator"],
    files: uiFiles("otp-field", [
      "context.ts",
      "field-relationships.ts",
      "otp-field-input.svelte",
      "otp-field-machine.ts",
      "otp-field-root.svelte",
      "otp-field-separator.svelte",
      "index.ts",
    ]),
  },
  {
    name: "pagination",
    type: "registry:ui",
    description: "Provides links for moving through a paged collection.",
    dependencies: ["@hugeicons/core-free-icons@4.3.0"],
    registryDependencies: ["local:button", "local:hugeicons-icon"],
    files: uiFiles("pagination", [
      "pagination.svelte",
      "pagination-content.svelte",
      "pagination-item.svelte",
      "pagination-link.svelte",
      "pagination-previous.svelte",
      "pagination-next.svelte",
      "pagination-ellipsis.svelte",
      "index.ts",
    ]),
  },
  {
    name: "popover",
    type: "registry:ui",
    description: "Displays interactive content beside a trigger or anchor.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("popover", [
      "popover-close.svelte",
      "popover-description.svelte",
      "popover-popup.svelte",
      "popover-root.svelte",
      "popover-title.svelte",
      "popover-trigger.svelte",
      "popover.types.ts",
      "index.ts",
    ]),
  },
  {
    name: "preview-card",
    type: "registry:ui",
    description: "Previews linked content when its trigger is hovered or focused.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("preview-card", [
      "preview-card-popup.svelte",
      "preview-card-root.svelte",
      "preview-card-trigger.svelte",
      "preview-card.types.ts",
      "index.ts",
    ]),
  },
  {
    name: "progress",
    type: "registry:ui",
    description: "Shows progress toward completing a task.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("progress", [
      "progress-root.svelte",
      "progress-label.svelte",
      "progress-track.svelte",
      "progress-indicator.svelte",
      "progress-value.svelte",
      "index.ts",
    ]),
  },
  {
    name: "radio-group",
    type: "registry:ui",
    description: "Lets a user choose one option from a set.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("radio-group", [
      "radio-group-root.svelte",
      "radio-group-item.svelte",
      "index.ts",
    ]),
  },
  {
    name: "scroll-area",
    type: "registry:ui",
    description: "Adds custom scrollbars to overflowing content.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("scroll-area", ["scroll-area.svelte", "scroll-bar.svelte", "index.ts"]),
  },
  {
    name: "select",
    type: "registry:ui",
    description: "Chooses a value from a popup list.",
    dependencies: [
      "@hugeicons/core-free-icons@4.3.0",
      "@hugeicons/svelte@1.1.5",
      "@shardsui/svelte@0.1.0-beta.0",
    ],
    registryDependencies: [],
    files: uiFiles("select", [
      "context.svelte.ts",
      "index.ts",
      "select-button.svelte",
      "select-group-label.svelte",
      "select-group.svelte",
      "select-item.svelte",
      "select-label.svelte",
      "select-parts.svelte",
      "select-popup.svelte",
      "select-root.svelte",
      "select-separator.svelte",
      "select-trigger.svelte",
      "select-value.svelte",
    ]),
  },
  {
    name: "separator",
    type: "registry:ui",
    description: "Visually or semantically separates content.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("separator", ["separator.svelte", "index.ts"]),
  },
  {
    name: "sheet",
    type: "registry:ui",
    description: "Displays overlay content from a chosen side of the viewport.",
    dependencies: ["@hugeicons/core-free-icons@4.3.0", "@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [
      "local:button",
      "local:dialog",
      "local:hugeicons-icon",
      "local:scroll-area",
    ],
    files: uiFiles("sheet", [
      "sheet-backdrop.svelte",
      "sheet-close.svelte",
      "sheet-description.svelte",
      "sheet-footer.svelte",
      "sheet-header.svelte",
      "sheet-panel.svelte",
      "sheet-popup.svelte",
      "sheet-title.svelte",
      "sheet-trigger.svelte",
      "sheet-viewport.svelte",
      "index.ts",
    ]),
  },
  {
    name: "sidebar",
    type: "registry:ui",
    description:
      "Builds responsive application navigation with collapsible desktop and mobile modes.",
    dependencies: [
      "@hugeicons/core-free-icons@4.3.0",
      "@hugeicons/svelte@1.1.5",
      "@shardsui/svelte@0.1.0-beta.0",
    ],
    registryDependencies: [
      "local:button",
      "local:drawer",
      "local:input",
      "local:scroll-area",
      "local:separator",
      "local:skeleton",
      "local:tooltip",
    ],
    files: uiFiles("sidebar", [
      "context.ts",
      "index.ts",
      "polymorphic.ts",
      "sidebar-content.svelte",
      "sidebar-footer.svelte",
      "sidebar-group-action.svelte",
      "sidebar-group-content.svelte",
      "sidebar-group-label.svelte",
      "sidebar-group.svelte",
      "sidebar-header.svelte",
      "sidebar-input.svelte",
      "sidebar-inset.svelte",
      "sidebar-menu-action.svelte",
      "sidebar-menu-badge.svelte",
      "sidebar-menu-button.svelte",
      "sidebar-menu-item.svelte",
      "sidebar-menu-skeleton.svelte",
      "sidebar-menu-sub-button.svelte",
      "sidebar-menu-sub-item.svelte",
      "sidebar-menu-sub.svelte",
      "sidebar-menu.svelte",
      "sidebar-provider.svelte",
      "sidebar-rail.svelte",
      "sidebar-root.svelte",
      "sidebar-separator.svelte",
      "sidebar-trigger.svelte",
    ]),
  },
  {
    name: "skeleton",
    type: "registry:ui",
    description: "Reserves space while content is loading.",
    dependencies: [],
    registryDependencies: [],
    files: uiFiles("skeleton", ["skeleton.svelte", "index.ts"]),
  },
  {
    name: "slider",
    type: "registry:ui",
    description: "Selects one or more values within a range.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("slider", [
      "slider-root.svelte",
      "slider-control.svelte",
      "slider-track.svelte",
      "slider-indicator.svelte",
      "slider-thumb.svelte",
      "slider-label.svelte",
      "slider-value.svelte",
      "index.ts",
    ]),
  },
  {
    name: "spinner",
    type: "registry:ui",
    description: "Indicates that an operation is in progress.",
    dependencies: ["@hugeicons/core-free-icons@4.3.0"],
    registryDependencies: ["local:hugeicons-icon"],
    files: uiFiles("spinner", ["spinner.svelte", "index.ts"]),
  },
  {
    name: "switch",
    type: "registry:ui",
    description: "Turns a setting on or off.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("switch", ["switch.svelte", "index.ts"]),
  },
  {
    name: "table",
    type: "registry:ui",
    description: "Displays structured data in rows and columns.",
    dependencies: [],
    registryDependencies: [],
    files: uiFiles("table", [
      "table.svelte",
      "table-header.svelte",
      "table-body.svelte",
      "table-footer.svelte",
      "table-row.svelte",
      "table-head.svelte",
      "table-cell.svelte",
      "table-caption.svelte",
      "index.ts",
    ]),
  },
  {
    name: "tabs",
    type: "registry:ui",
    description: "Switches between related panels in the same region.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("tabs", [
      "tabs-root.svelte",
      "tabs-list.svelte",
      "tabs-tab.svelte",
      "tabs-panel.svelte",
      "tabs-indicator.svelte",
      "tabs-styles.ts",
      "context.ts",
      "index.ts",
    ]),
  },
  {
    name: "textarea",
    type: "registry:ui",
    description: "Collects multiline user input.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("textarea", ["textarea.svelte", "index.ts"]),
  },
  {
    name: "toast",
    type: "registry:ui",
    description: "Displays transient status and action feedback.",
    dependencies: ["@hugeicons/core-free-icons@4.3.0", "@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: ["local:button", "local:hugeicons-icon"],
    files: uiFiles("toast", [
      "anchored-toast-provider.svelte",
      "anchored-toast-stack.svelte",
      "index.ts",
      "toast-icon.svelte",
      "toast-manager.ts",
      "toast-managers.ts",
      "toast-portal.svelte",
      "toast-provider.svelte",
      "toast-stack.svelte",
      "toast.types.ts",
    ]),
  },
  {
    name: "toggle",
    type: "registry:ui",
    description: "Switches a single control between pressed and unpressed states.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("toggle", ["toggle.svelte", "toggle-variants.ts", "index.ts"]),
  },
  {
    name: "toggle-group",
    type: "registry:ui",
    description: "Groups related toggle controls with shared selection behavior.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: ["local:separator", "local:toggle"],
    files: uiFiles("toggle-group", [
      "toggle-group-root.svelte",
      "toggle-group-item.svelte",
      "toggle-group-separator.svelte",
      "toggle-group-styles.ts",
      "context.ts",
      "index.ts",
    ]),
  },
  {
    name: "toolbar",
    type: "registry:ui",
    description: "Groups controls with coordinated keyboard navigation.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("toolbar", [
      "toolbar-button.svelte",
      "toolbar-group.svelte",
      "toolbar-input.svelte",
      "toolbar-link.svelte",
      "toolbar-root.svelte",
      "toolbar-separator.svelte",
      "toolbar.types.ts",
      "index.ts",
    ]),
  },
  {
    name: "tooltip",
    type: "registry:ui",
    description: "Shows a short description when a trigger is hovered or focused.",
    dependencies: ["@shardsui/svelte@0.1.0-beta.0"],
    registryDependencies: [],
    files: uiFiles("tooltip", [
      "context.ts",
      "handle.svelte.ts",
      "tooltip-popup.svelte",
      "tooltip-provider.svelte",
      "tooltip-root.svelte",
      "tooltip-trigger.svelte",
      "tooltip.types.ts",
      "index.ts",
    ]),
  },
]);
