export type DocsManifestEntry = {
  id: string;
};

export function defineDocsManifest<const Entries extends readonly DocsManifestEntry[]>(
  entries: Entries,
): Entries {
  return entries;
}

export const docsManifest = defineDocsManifest([
  { id: "index" },
  { id: "get-started" },
  { id: "styling" },
  { id: "radix-migration" },
  { id: "skills" },
  { id: "changelog" },
  { id: "roadmap" },
  { id: "components/accordion" },
  { id: "components/alert" },
  { id: "components/alert-dialog" },
  { id: "components/autocomplete" },
  { id: "components/avatar" },
  { id: "components/badge" },
  { id: "components/breadcrumb" },
  { id: "components/button" },
  { id: "components/calendar" },
  { id: "components/card" },
  { id: "components/checkbox" },
  { id: "components/checkbox-group" },
  { id: "components/collapsible" },
  { id: "components/combobox" },
  { id: "components/command" },
  { id: "components/context-menu" },
  { id: "components/date-picker" },
  { id: "components/dialog" },
  { id: "components/drawer" },
  { id: "components/empty" },
  { id: "components/field" },
  { id: "components/fieldset" },
  { id: "components/form" },
  { id: "components/frame" },
  { id: "components/group" },
  { id: "components/input" },
  { id: "components/input-group" },
  { id: "components/kbd" },
  { id: "components/label" },
  { id: "components/menu" },
  { id: "components/meter" },
  { id: "components/number-field" },
  { id: "components/otp-field" },
  { id: "components/pagination" },
  { id: "components/popover" },
  { id: "components/preview-card" },
  { id: "components/progress" },
  { id: "components/radio-group" },
  { id: "components/scroll-area" },
  { id: "components/select" },
  { id: "components/segmented-control" },
  { id: "components/separator" },
  { id: "components/sheet" },
  { id: "components/skeleton" },
  { id: "components/slider" },
  { id: "components/spinner" },
  { id: "components/switch" },
  { id: "components/table" },
  { id: "components/tabs" },
  { id: "components/textarea" },
  { id: "components/toast" },
  { id: "components/toggle" },
  { id: "components/toggle-group" },
  { id: "components/toolbar" },
  { id: "components/tooltip" },
  { id: "hooks/use-media-query" },
  { id: "hooks/use-copy-to-clipboard" },
]);
