<script module lang="ts">
  import {
    Add01Icon,
    AlertCircleIcon,
    ArrowDown01Icon,
    ArrowLeft01Icon,
    ArrowRight01Icon,
    ArrowUp01Icon,
    Bookmark02Icon,
    BookOpen01Icon,
    Cancel01Icon,
    CopyIcon,
    ArrowTurnBackwardIcon,
    BoxIcon,
    Delete02Icon,
    ChevronDownIcon,
    DollarSignIcon,
    Download01Icon,
    FloppyDiskIcon,
    Folder01Icon,
    House01Icon,
    InboxIcon,
    InformationCircleIcon,
    Link01Icon,
    Mail01Icon,
    MinusSignIcon,
    MoreHorizontalIcon,
    NextIcon,
    Notification02Icon,
    PanelsTopLeftIcon,
    PauseIcon,
    PencilIcon,
    PercentIcon,
    PlayIcon,
    PlusSignIcon,
    PreviousIcon,
    ReloadIcon,
    Route01Icon,
    Search01Icon,
    SearchAddIcon,
    SearchMinusIcon,
    Settings01Icon,
    Share03Icon,
    Share08Icon,
    StarIcon,
    TextAlignCenterIcon,
    TextAlignLeftIcon,
    TextAlignRightIcon,
    TextBoldIcon,
    TextItalicIcon,
    TextUnderlineIcon,
    Tick02Icon,
    UnfoldMoreIcon,
    UserIcon,
    ViewIcon,
    ViewOffSlashIcon,
    VolumeHighIcon,
    VolumeMute02Icon,
  } from "@hugeicons/core-free-icons";
  import type { HugeiconData, HugeiconsIconProps } from "@coss-sv/ui";

  const icons = {
    "alert-circle": AlertCircleIcon,
    "align-center": TextAlignCenterIcon,
    "align-left": TextAlignLeftIcon,
    "align-right": TextAlignRightIcon,
    "arrow-down": ArrowDown01Icon,
    "arrow-left": ArrowLeft01Icon,
    "arrow-right": ArrowRight01Icon,
    "arrow-up": ArrowUp01Icon,
    bell: Notification02Icon,
    bookmark: Bookmark02Icon,
    bold: TextBoldIcon,
    book: BookOpen01Icon,
    cancel: Cancel01Icon,
    check: Tick02Icon,
    "chevron-down": ChevronDownIcon,
    copy: CopyIcon,
    currency: DollarSignIcon,
    download: Download01Icon,
    eye: ViewIcon,
    "eye-off": ViewOffSlashIcon,
    folder: Folder01Icon,
    home: House01Icon,
    inbox: InboxIcon,
    "info-circle": InformationCircleIcon,
    italic: TextItalicIcon,
    link: Link01Icon,
    mail: Mail01Icon,
    minus: MinusSignIcon,
    more: MoreHorizontalIcon,
    next: NextIcon,
    package: BoxIcon,
    panels: PanelsTopLeftIcon,
    pause: PauseIcon,
    pencil: PencilIcon,
    percent: PercentIcon,
    play: PlayIcon,
    plus: Add01Icon,
    "plus-sign": PlusSignIcon,
    previous: PreviousIcon,
    redo: ArrowTurnBackwardIcon,
    reset: ReloadIcon,
    route: Route01Icon,
    save: FloppyDiskIcon,
    search: Search01Icon,
    share: Share03Icon,
    "share-2": Share08Icon,
    star: StarIcon,
    settings: Settings01Icon,
    trash: Delete02Icon,
    underline: TextUnderlineIcon,
    "unfold-more": UnfoldMoreIcon,
    user: UserIcon,
    "volume-high": VolumeHighIcon,
    "volume-mute": VolumeMute02Icon,
    "zoom-in": SearchAddIcon,
    "zoom-out": SearchMinusIcon,
  } as const;

  export type FixtureIconName = keyof typeof icons;
  type Props = Omit<HugeiconsIconProps, "children" | "icon" | "strokeWidth"> & {
    name: FixtureIconName;
  };
</script>

<script lang="ts">
  import { HugeiconsIcon } from "@coss-sv/ui";

  let { name, ...props }: Props = $props();
  const icon = $derived(icons[name] as HugeiconData);
</script>

<HugeiconsIcon {icon} strokeWidth={2} {...props} />
